---
title: "Dewright"
output: html_document
---

```{r}
install.packages("lpSolveAPI")





```
Number ### 1

y1 = 6x1 + 4x2 + 5x3 - 50
y2 = 8x1 + 7x2 + 5x3 - 75


P = 20x1 + 15x2 + 25x3




Number ### 2

Management Objective Function in terms of x and y

maximize Z: 12x1 + 9x2 + 15x3 - 6 y1p - 6 y1m - 3 y2m;




Number ### 3

```{r}
library(lpSolveAPI)

gp <-  read.lp("EmaxCorp.lp")  # create an lp object gp

gp                            # display gp

```
Model name: 
            x1    x2    x3   y1p   y1m   y2m   y2p       
Maximize    12     9    15    -6    -6    -3     0       
R1           6     4     5    -1     1     0     0  =  50
R2           8     7     5     0     0     1    -1  =  75
Kind       Std   Std   Std   Std   Std   Std   Std       
Type      Real  Real  Real  Real  Real  Real  Real       
Upper      Inf   Inf   Inf   Inf   Inf   Inf   Inf       
Lower        0     0     0     0     0     0     0  

```{r}
solve(gp)
get.objective(gp)
get.variables(gp)
```
[1] 0
[1] 125
[1] 0.000000 8.333333 3.333333 0.000000 0.000000 0.000000 0.000000


Findings

Optimal solution is Z = 125

Variable values (appear in order of formulation) are:
x1 = 0
x2 = 8.33
x3 = 3.33
y1p = 0
y1m = 0
y2m = 0
y2p = 0
